engines:
  jshint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
      - test

ratings:
  paths:
  - index.js
  - lib/**

exclude_paths:
  - bin
  - dist
  - examples
