engines:
  jshint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude-paths:
    - examples/**
    - dist/**

ratings:
  paths:
  - index.js
  - lib/**
